# Generated by Django 4.2 on 2023-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject_name',
            field=models.CharField(default='test', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
