# Generated by Django 4.2 on 2023-04-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_question_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject_name',
        ),
    ]
