# Generated by Django 4.2 on 2023-04-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_type'),
        ('mcq', '0003_remove_question_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
            preserve_default=False,
        ),
    ]
