# Generated by Django 4.2 on 2023-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='course',
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
