# Generated by Django 4.2 on 2023-04-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_semester_course_semester_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='course',
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
