# Generated by Django 4.2 on 2023-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_semester_course_semester_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hasSemester',
            field=models.BooleanField(default=True, verbose_name='has_semesters'),
        ),
    ]
