# Generated by Django 4.2 on 2023-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_hassemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hasSemester',
            field=models.BooleanField(default=True, verbose_name='has semesters'),
        ),
    ]
